nelmio_api_doc:
    documentation:
        info:
            title: TaskFlow API
            description: API REST sécurisée pour une application de gestion de projets agile.
            version: 1.0.0
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - bearerAuth: []
    areas:
        path_patterns:
            - ^/auth
            - ^/me$
            - ^/users
            - ^/projects
            - ^/tasks
            - ^/tags